### ISSUE TITLE
Cannot deserialize field of type Map<String, CustomClass> from json

### ISSUE THREAD

**Issue by Ug-Projekt** [gmpassos/reflection_factory#11] opened 2023-01-03 08:28 UTC
First of all thank you for your awesome work, I'm using this library in a big project of our software company, you save my a lot of time,

```
//This is my entity:

@EnableReflection()
class Person {
  String name;
  String email;
  Map<String, Address> address; //There is the line that produce error
  Person(this.name, this.email, this.address);
}

@EnableReflection()
class Address {
  String uuid;
  String country;
  String city;
  Address(this.uuid, this.country, this.city);
}

//And using it like this:

Future<void> main(List<String> args) async {
  final person = Person("Person", "Email", {"123456": Address("123456", "Country", "City")});
  final jsonMapOfPerson = person.toJsonMap(); //There is no error of serialization
  final personFromJson = Person$fromJson(jsonMapOfPerson!); //But this is not.
  print("personFromJson: $personFromJson");
}
```

above code produces error looks like below:

```
Error invoking[0]>
  - constructor: ConstructorReflection{ class: Person, name: , normalParameters: [ParameterReflection{type: String, name: name, required}, ParameterReflection{type: String, name: email, required}, ParameterReflection{type: Map<String,Address>, name: address, required}], optionalParameters: [], namedParameters: {} }
  - map: {address: {123456: {city: City, country: Country, uuid: 123456}}, email: Email, name: Person}
  - methodInvocation: MethodInvocation{normalParameters: [Person, Email, {123456: {city: City, country: Country, uuid: 123456}}], optionalParameters: [], namedParameters: {}}
  - error: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, Address>' of 'address'

Unhandled exception:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, Address>' of 'address'

```

but everything is perfect and no error if I try to change the type of field `Map<String, Address> address;` to `List<Address> address;` looks like this:

```
@EnableReflection()
class Person {
  String name;
  String email;
  List<Address> address;
  Person(this.name, this.email, this.address);
}

@EnableReflection()
class Address {
  String uuid;
  String country;
  String city;
  Address(this.uuid, this.country, this.city);
}

Future<void> main(List<String> args) async {
  final person = Person("Person", "Email", [Address("123456", "Country", "City")]);
  final jsonMapOfPerson = person.toJsonMap();
  final personFromJson = Person$fromJson(jsonMapOfPerson!);
  print("personFromJson: $personFromJson");
}
```

is there any way to do this?

thank you.

**Comment by Ug-Projekt** [comment] 2023-01-03 08:52
looks like What I want is `FieldResolver`, lets start some research.

**Comment by gmpassos** [comment] 2023-01-03 18:57
It should work. I will make some tests in the next days. And yes, the List version works because we use it all over the place and tested it better.

I think that the issue is to create a casted Map. For now you can use a factory constructor that receives a Map<String, dynamic> and fixes your address parameter to Map<String, Address> and passes to a private constructor.

**Comment by gmpassos** [comment] 2023-01-03 23:55
I have identified the error and I already have a working fix. Just making some extra unit tests...

**Comment by gmpassos** [comment] 2023-01-04 00:18
You can try it with:

```yaml
dependency_overrides:
  reflection_factory:
    git:
      url: https://github.com/gmpassos/reflection_factory.git
      ref: fix-map-casting
```

Let me know if it works. Don't forget to rebuild the reflection code.

**Comment by gmpassos** [comment] 2023-01-04 21:23
Fixed on version v1.2.18:

https://pub.dev/packages/reflection_factory

**Comment by Ug-Projekt** [comment] 2023-01-05 00:05
Thank you for your reply, the v1.2.18 version is now working as expected with my sample code above but the new version is generates new error like:
```
Error invoking[0]>
  - constructor: ConstructorReflection{ class: RpcCallRequest, name: , normalParameters: [], optionalParameters: [], namedParameters: {argument: ParameterReflection{type: Map<String,dynamic>, name: argument, required}, methodName: ParameterReflection{type: String, name: methodName, required}, requestId: ParameterReflection{type: String, name: requestId, required}, timeoutMilliseconds: ParameterReflection{type: int, name: timeoutMilliseconds, required}} }
  - map: {argument: {step: 1}, methodName: incAndGet, requestId: 8afa83db-7a25-4f03-98b5-c89c472b27cd, timeoutMilliseconds: 15000}
  - methodInvocation: MethodInvocation{normalParameters: [], optionalParameters: [], namedParameters: {argument: {step: 1}, methodName: incAndGet, requestId: 8afa83db-7a25-4f03-98b5-c89c472b27cd, timeoutMilliseconds: 15000}}
  - error: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' of 'argument'

Error invoking[0]>
  - constructor: ConstructorReflection{ class: RpcCallRequest, name: , normalParameters: [], optionalParameters: [], namedParameters: {argument: ParameterReflection{type: Map<String,dynamic>, name: argument, required}, methodName: ParameterReflection{type: String, name: methodName, required}, requestId: ParameterReflection{type: String, name: requestId, required}, timeoutMilliseconds: ParameterReflection{type: int, name: timeoutMilliseconds, required}} }
  - map: {argument: {step: 1}, methodName: incAndGet, requestId: 8afa83db-7a25-4f03-98b5-c89c472b27cd, timeoutMilliseconds: 15000}
  - methodInvocation: MethodInvocation{normalParameters: [], optionalParameters: [], namedParameters: {argument: {step: 1}, methodName: incAndGet, requestId: 8afa83db-7a25-4f03-98b5-c89c472b27cd, timeoutMilliseconds: 15000}}
  - error: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' of 'argument'
```

anyhow above test code is working for me with `Map<String, CustomType>`, I will let you know if I find the new kind of error whatever this is my mistake or not.
thank you

**Comment by gmpassos** [comment] 2023-01-05 00:16
I'm looking for a similar bug now...

**Comment by Ug-Projekt** [comment] 2023-01-05 00:19
I found the reason of above error,  `Map<String, CustomClass>` is working perfect, but also I have used `reflection_factory` in many place of my code with type `Map<String, dynamic>`, so type of `Map<String, dynamic>` is failed with version: `v1.2.18` and no error with version `v1.2.17`

 here is the simple demonstration code:

This code is working on `v1.2.17` but on `v1.2.18` is not.
```
@EnableReflection()
class Person {
  DateTime createdAt;
  String name;
  String email;
  Map<String, dynamic> address; //
  Person(this.createdAt, this.name, this.email, Map<String, dynamic> address) : address = address;
}

@EnableReflection()
class Address {
  String uuid;
  String country;
  String city;
  Address(this.uuid, this.country, this.city);
}

Future<void> main(List<String> args) async {
  final person = Person(DateTime.now(), "Person", "Email", {"123456": Address("123456", "Country", "City")});
  final jsonMapOfPerson = person.toJsonMap();
  final instance = Person$fromJson(jsonMapOfPerson!);
  print("personFromJson: $instance");
}

```

**Comment by gmpassos** [comment] 2023-01-05 00:28
Please, true the branch `fix-castMapType`

**Comment by Ug-Projekt** [comment] 2023-01-05 00:29
> It should work. I will make some tests in the next days. And yes, the List version works because we use it all over the place and tested it better.
> 
> I think that the issue is to create a casted Map. For now you can use a factory constructor that receives a Map<String, dynamic> and fixes your address parameter to Map<String, Address> and passes to a private constructor.

This is working for me at this moment, thanks :)

**Comment by gmpassos** [comment] 2023-01-05 00:30
I will release a new version soo, but I need some extra tests...

**Comment by Ug-Projekt** [comment] 2023-01-05 00:39
> Please, try the branch `fix-castMapType`
> 
> ```yaml
> dependency_overrides:
>   reflection_factory:
>     git:
>       url: https://github.com/gmpassos/reflection_factory.git
>       ref: fix-castMapType
> ```
> 
> If possible, confirm if this branch fixes your new issue with `Map<String, dynamic>`

Confirmed, this is works both `Map<String, dynamic>` and `Map<String, Address>`,

I'm so sorry for my slow reply, our g0vernment is prevent us to open Github so github cannot open a while...
thank you.

**Comment by gmpassos** [comment] 2023-01-05 01:30
Done:

reflection_factory: ^1.2.19

**Closed by gmpassos** 2023-01-05 01:30 UTC

**Comment by gmpassos** [comment] 2023-01-05 06:29
Please, check the newer version:
reflection_factory: ^1.2.21

I have upgraded to `analyzer: ^5.4.0`

Let me know if it works well.

**Comment by Ug-Projekt** [comment] 2023-01-06 12:13
> @Ug-Projekt,
> 
> Please, check the newer version: `reflection_factory: ^1.2.21`
> 
> I have upgraded to `analyzer: ^5.4.0`
> 
> Let me know if it works well.

Confirmed.
My project works with `reflection_factory: ^1.2.21`

thank you.
